import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import SessionProvider from "./SessionProvider";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Duck Racer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
